### ISSUE TITLE
How crazy would it be to try and incorporate a mouse into the PCB?

### ISSUE THREAD

**Issue by shaleh** [TeXitoi/keyseebee#13]
I like the idea of the chordie design, but I want the number of keys in keyseebee.

The trackball design there uses 6 wires.

**Comment by TeXitoi** [comment]
You mean https://github.com/kbjunky/Chordie ?

There is a bunch of pads available on the backside. Should be enough for hacking something like that. You can see them on a photo on the readme.

**Comment by TeXitoi** [comment]
Yeah, you have spi with cs on pa[4567] +gnd+ 3.3v on the back, exactly the pin you need for the trackball controller of the chordie. You'll need some code to create a rust driver of the trackball controller, and a bit of glue in keyseebee to manage the 2 devices.

**Comment by shaleh** [comment]
Excellent. Thanks.
