### ISSUE TITLE
0.1 LDO fix

### ISSUE THREAD

**Issue by keyboard-magpie** [TeXitoi/keyseebee#6]
A friend and I have some 0.1 keyseebee PCBs we're building up- is it possible to see a hi res photo, or have a description of the fix needed? I can see in some photos the LDO is at an unusual angle.

**Comment by TeXitoi** [comment]
The alone leg must be at 1 o'clock. More info here: https://github.com/TeXitoi/keyseebee/blob/master/pcb/gerbers/CHANGELOG.md#v01-2020-08-02

Why did you printed the v0.1 and not v0.2?

**Comment by keyboard-magpie** [comment]
Got it! :D Multimeter and such.
No idea why  did, i think he downloaded just before 0.2 was released.
Up and running now though.

https://cdn.discordapp.com/attachments/760085292048187442/783447743632244796/image0.jpg

**Comment by TeXitoi** [comment]
Exactly. I hope you've soldered the diodes in the good direction. If not, that should be fixable in the firmware.

**Comment by keyboard-magpie** [comment]
Oh, hadn't spotted that one! Presume they're opposite to silkscreen marking then?

**Comment by TeXitoi** [comment]
yup, dash up.

**Comment by keyboard-magpie** [comment]
Perfect thanks. Will pass this on.

**Comment by TeXitoi** [comment]
yup, dash up.
