### ISSUE TITLE
STM32F072CBT6 link expired in Readme.md

### ISSUE THREAD

**Issue by mejobloggs** [TeXitoi/keyseebee#7]
BOM section: https://github.com/TeXitoi/keyseebee/blob/master/README.md#bill-of-materials

Link for STM32F072CBT6 says product no longer exists.

Can you please update?

I would provide alternative link myself but I'm new to electronics and not sure if I will get the right product :)

STM32F072CBT6 seems scarce on AliExpress now?

**Comment by TeXitoi** [comment]
Link updated. Thanks for letting me know.

If you build a KeySeeBee, please keep me informed!

Enjoy!
